# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: srdionizio
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: pessoal
# "service" is the name of this project. This will also be added to your AWS resource names.
service: datalake-dionizio

provider:
  name: aws
  runtime: python3.10
  region: us-east-1

functions:
  hello:
    handler: app/lambda/request_posts.lambda_handler
    timeout: 60
    memorySize: 128 
    events:
      - httpApi:
          path: /datalake-dionizio
          method: post

plugins:
  - serverless-python-requirements
  - serverless-lift
