# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: srdionizio
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: pessoal
# "service" is the name of this project. This will also be added to your AWS resource names.
service: datalake-dionizio

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
        - s3:DeleteObject
      Resource:
        - arn:aws:s3:::datalake-dados-dionizio/*
    - Effect: Allow
      Action:
        - s3:ListBucket
      Resource:
        - arn:aws:s3:::datalake-dados-dionizio

functions:
  hello:
    handler: request_cars.lambda_handler
    timeout: 60
    memorySize: 128 
    events:
      - httpApi:
          path: /datalake-dionizio
          method: post

plugins:
  - serverless-python-requirements
  - serverless-lift
